name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: my-image

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Path
        run: pwd
      - name: Run tests
        run: docker build SampleCSharpDockerSolution --file SampleCSharpDockerSolution/SampleCSharpDockerProject/Dockerfile --tag docker.pkg.github.com/zerowasteteam/samplecsharpdocker/my-image:latest
  # Push image to GitHub Package Registry.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GHDockerToken }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image 
        run: docker push docker.pkg.github.com/zerowasteteam/samplecsharpdocker/my-image:latest 