name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ZeroWasteTeam/SampleCSharpDocker
        username: nachiapan@gmail.com
        password: John28nash
        registry: docker.pkg.github.com
        dockerfile: SampleCSharpDockerSolution/SampleCSharpDockerProject/Dockerfile
        context: SampleCSharpDockerSolution
        tags: "latest,another"
